---
# create standby.signal file in data directory

# configure streaming WAL primary_conninfo needs a libpq connection string (ip
# address + other details needed to connect to primary server)

# since we want the standby to be able to operate as the primary, we need to
# configure the WAL archiving, connections, and auth like the primary example:
# primary_conninfo = 'host=192.168.1.50 port=5432 user=foo password=foopass
# options=''-c wal_sender_timeout=5000''' restore_command = 'cp
# /path/to/archive/%f %p' archive_cleanup_command = 'pg_archivecleanup
# /path/to/archive %r'

# add the following line to the postgresql.conf file on the standby The standby
# connects to the primary that is running on host 192.168.1.50 and port 5432 as
# the user "foo" whose password is "foopass". primary_conninfo =
# 'host=192.168.1.50 port=5432 user=foo password=foopass'

# use the replication slot on the primary (in file after the primary_conninfo)
# primary_slot_name = 'node_a_slot' repmgr
# https://www.repmgr.org/docs/current/quickstart-standby-clone.html must be
# done before the standby is put into read only mode (therefore not idempotent)
- name: Stop service postgres, if running
  ansible.builtin.systemd_service:
    name: postgresql
    state: stopped
  become: true

# https://www.repmgr.org/docs/current/quickstart-standby-clone.html
- name: Run repmgr to dry run clone
  ansible.builtin.command: "repmgr -h {{ pg_primary_ip }} -U repmgr -d repmgr standby clone --dry-run -F"
  environment:
    PGPASSFILE: /etc/postgresql/{{ pg_version }}/main/pgpass
  become: true
  become_user: postgres
  register: dry_run_clone_results
  changed_when: false

- name: Print out the dry_run_clone_results
  ansible.builtin.debug:
    var: dry_run_clone_results.stderr_lines

- name: Confirm clone
  ansible.builtin.pause:
    prompt: "Are you sure you want to go through with this clone? ctrl-c c to continue ctrl-c a to abort"

- name: Run repmgr to force clone standby from primary
  ansible.builtin.command: "repmgr -h {{ pg_primary_ip }} -U repmgr -d repmgr standby clone -F"
  environment:
    PGPASSFILE: /etc/postgresql/{{ pg_version }}/main/pgpass
  register: clone_results
  become: true
  become_user: postgres
  # changed_when: "'NOTICE: standby clone (using pg_basebackup) complete' in clone_results.stderr_lines"
  changed_when: true
  async: 18000 # 5 hours
  poll: 20

- name: Print out the clone_results
  ansible.builtin.debug:
    var: clone_results.stderr_lines

- name: Start service postgres
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
  become: true

- name: Waits for port 5432 to be available, don't check for initial 10 seconds
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 5432
    delay: 10
    state: started

# https://www.repmgr.org/docs/current/quickstart-register-standby.html
- name: Run repmgr to force register the standby
  ansible.builtin.command: repmgr standby register -F
  environment:
    PGPASSFILE: /etc/postgresql/{{ pg_version }}/main/pgpass
  become: true
  become_user: postgres
  register: register_results
  # changed_when: "'INFO: standby registration complete' in register_results.stderr_lines"
  # failed_when: ...
  changed_when: true

- name: Print out the register_standby_results
  ansible.builtin.debug:
    var: register_results.stderr_lines

# run some sql... to confirm clone?
# TODO: can probably make this fail if query is not what we expect
- name: Do some sql to test for the existence of lard...?
  community.postgresql.postgresql_query:
    login_db: lard
    query: select count(*) from timeseries
  register: query_results
  become: true
  become_user: postgres

- name: Print out the query
  ansible.builtin.debug:
    var: query_results
