---
- name: Check if dump file is already there
  ansible.builtin.stat:
    get_checksum: false
    path: '{{ recovery_mount_point }}/{{ recovery_filename }}'
  register: register_backup

- name: File exists?
  ansible.builtin.debug:
    msg: The backup file exists
  when: register_backup.stat.exists

- name: Copy backup file to server from s3
  amazon.aws.s3_object:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    bucket: lard
    dest: '{{ recovery_mount_point }}/{{ recovery_filename }}'
    mode: get
    object: backups/{{ recovery_filename }}
    rgw: true
    s3_url: '{{ s3_url }}'
  register: move_backup_from_s3
  when: not register_backup.stat.exists

- name: Print out move_backup_from_s3
  ansible.builtin.debug:
    var: move_backup_from_s3.stderr_lines

- name: Change ownership of file
  ansible.builtin.file:
    group: postgres
    mode: "0775"
    owner: postgres
    path: '{{ recovery_mount_point }}/{{ recovery_filename }}'
  become: true

- name: Set venv interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: '{{ recovery_mount_point }}/.venv/postgres/bin/python3'

- name: Create a lard databases
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: lard

- name: Restore database dump
  vars:
    filename: '{{ recovery_mount_point }}/{{ recovery_filename }}'
  ansible.builtin.command: pg_restore -U postgres -d lard -j 4 {{ filename }}
  async: 10000
  become: true
  become_user: postgres
  changed_when: false
  poll: 0
  register: dump_restore

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/async_status_module.html
- name: Check if dump complete
  ansible.builtin.async_status:
    jid: '{{ dump_restore.ansible_job_id }}'
  become: true
  become_user: postgres
  delay: 30
  register: job_result
  retries: 300
  until: job_result.finished

- name: Clean up async file
  ansible.builtin.async_status:
    jid: '{{ dump_restore.ansible_job_id }}'
    mode: cleanup
  become: true
  become_user: postgres
