[package]
name = "lard_egress"
version = "0.1.0"
edition.workspace = true

[dependencies]
axum.workspace = true
bb8.workspace = true
bb8-postgres.workspace = true
chrono.workspace = true
drops = { path = "../drops" }
util = { path = "../util" }
postgres-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true