[package]
name = "lard_egress"
version = "0.1.0"
edition.workspace = true

[features]
integration_tests = []
mock_auth = []

[dependencies]
axum.workspace = true
bb8.workspace = true
bb8-postgres.workspace = true
chrono.workspace = true
chronoutil.workspace = true
csv.workspace = true
pg_interval.workspace = true
postgres-types.workspace = true
rust-s3.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
util = { path = "../util" }
tower-http.workspace = true
http.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
