# RESERVATIONS - do not add entries for these here
# station_ids in the  30000s are used to test ingestion
#
# NOTE: don't forget to add permits for your timeseries, or you might wonder
# why they aren't showing up

# Generic timeseries shared by a lot of tests, all station 20001
[[ts]]
label = {
    station_id = 20001,
    param_id = 211, #TA
    type_id = 508,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}
[[ts]]
label = {
    station_id = 20001,
    param_id = 211, #TA
    type_id = 501,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}
[[ts]]
label = {
    station_id = 20001,
    param_id = 225, #TGX
    type_id = 501,
    #level = None
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}
[[ts]]
label = {
    station_id = 20001,
    param_id = 1022, #KLOBS
    type_id = 501,
    #level = 200, # TODO
    sensor = 0,
}
data = {
    repeated_nonscalar = {
        value = "2024-01-01T00:00:00+00:00",
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}

# Older data used to test latest
[[ts]]
label = {
    station_id = 20002,
    param_id = 211, #TA
    type_id = 501,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2020-01-01T00:00:00+00:00",
        stop = "2020-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}

# Restricted data
[[ts]] # permitid 5
label = {
    station_id = 40001,
    param_id = 211, #TA
    type_id = 508,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}
[[ts]] # permitid 6
label = {
    station_id = 40002,
    param_id = 211, #TA
    type_id = 508,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}

# Windrose
[[ts]]
label = {
    station_id = 20001,
    param_id = 81, #FF
    type_id = 501,
    level = 1000,
    sensor = 0,
}
data = {
    irregular = {
        values = [
            {
              time = "2025-01-01T00:00:00+00:00",
              value = 0.1,
            },
            {
              time = "2025-01-01T01:00:00+00:00",
              value = 0.4,
            },
            {
              time = "2025-01-01T02:00:00+00:00",
              value = 21,
            },
            {
              time = "2025-01-01T03:00:00+00:00",
              value = 37,
            },
        ]
    }
}
[[ts]]
label = {
    station_id = 20001,
    param_id = 61, #DD
    type_id = 501,
    level = 1000,
    sensor = 0,
}
data = {
    irregular = {
        values = [
            {
              time = "2025-01-01T00:00:00+00:00",
              value = 220,
            },
            {
              time = "2025-01-01T01:00:00+00:00",
              value = 30,
            },
            {
              time = "2025-01-01T02:00:00+00:00",
              value = 330,
            },
            {
              time = "2025-01-01T03:00:00+00:00",
              value = 15,
            },
        ]
    }
}
[[ts]]
label = {
    station_id = 20002,
    param_id = 81, #FF
    type_id = 501,
    level = 1000,
    sensor = 0,
}
data = {
    repeated = {
        value = 0,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}

# Calculations
[[ts]]
label = {
    station_id = 20001,
    param_id = 262, #UU
    type_id = 501,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 1,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}
[[ts]]
label = {
    station_id = 20001,
    param_id = 173, #PA
    type_id = 501,
    level = 200,
    sensor = 0,
}
data = {
    repeated = {
        value = 1,
        start = "2024-01-01T00:00:00+00:00",
        stop = "2024-01-01T12:00:00+00:00",
        interval = "PT1H",
    }
}
