[workspace]
members = [
  "egress",
  "ingestion",
  "integration_tests",
  "util",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
async-trait = "0.1.89"
axum = "0.8.9"
bb8 = "0.9.1"
bb8-postgres = "0.9.0"
bytes = "1.11.1"
chrono = { version = "0.4.45", features = ["serde"] }
chronoutil = "0.2.7"
clap = { version = "4.6.1", features = ["derive"] }
csv = "1.4.0"
futures = "0.3.32"
http = "1.4.2"
itertools = "0.14.0"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
metrics = "0.24.6"
# feature tampering here is to get rid of rustls for better build times
metrics-exporter-prometheus = { version = "0.18.3", default-features = false, features= ["http-listener"] }
pg_interval = "0.5.0"
postgres-types = { version = "0.2.13", features = ["derive", "with-chrono-0_4"] }
quick-xml = { version = "0.40.1", features = [ "serialize", "overlapped-lists" ] }
rdkafka = "0.39.0"
regex = "1.12.4"
# feature tampering here is to get rid of rustls for better build times
reqwest = { version = "0.13.4", default-features = false, features = ["json", "native-tls", "charset", "http2", "system-proxy"] }
rust-s3 = "0.37.2"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.27.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "signal"] }
tokio-postgres = { version = "0.7.17", features = ["with-chrono-0_4"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
toml = "1.1.2"
tower-http = { version = "0.6.11", features = ["compression-full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
