[package]
name = "lard_ingestion"
version = "0.1.0"
edition.workspace = true

[features]
default = ["legacy"]
legacy = []
next = []
integration_tests = ["legacy", "next"]

[dependencies]
axum.workspace = true
bb8.workspace = true
bb8-postgres.workspace = true
chrono.workspace = true
chronoutil.workspace = true
util = { path = "../util" }
csv.workspace = true
futures.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
quick-xml.workspace = true
rdkafka.workspace = true
postgres-types.workspace = true
pg_interval.workspace = true
regex.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
