---
- name: Create security groups
  openstack.cloud.security_group:
    cloud: "{{ ostack_cloud }}"
    region_name: "{{ ostack_region }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    security_group_rules: "{{ item.security_group_rules }}"
  loop: "{{ ostack_network_security_groups }}"
  loop_control:
    label: "Updating security group {{ item.name }}"
