package port

import (
	kdvh "migrate/kdvh/db"
)

// Functions that try to recover the original pair of `controlinfo` and `useinfo` (see `kdvh/import/flags/flags.go`)
// generated by Kvalobs for an observation, based on `kdvh.Obs.Flags` and `kdvh.Obs.Data`
// Different KDVH tables need different ways to perform this conversion.
// It returns a generic slice, used by pgx for the postgres COPY command.
type ConvertFunction func(*kdvh.Obs, *kdvh.TsInfo) ([]any, error)
type Table struct {
	Name string // Name of the DATA table
	// TODO: remove this after dumping the elem tables
	Convert     ConvertFunction // How to convert the dumped csv data for the given table
	ImportUntil int             // Data will be imported until this year (exclusive)
}

func NewTable(name string, fn ConvertFunction, year int) *Table {
	return &Table{
		Name:        name,
		Convert:     fn,
		ImportUntil: year,
	}
}

var IMPORT_TABLES map[string]*Table = map[string]*Table{
	"T_EDATA":      NewTable("T_EDATA", convertEdata, 3000),
	"T_METARDATA":  NewTable("T_METARDATA", convert, 3000),
	"T_ADATA":      NewTable("T_ADATA", convert, 2006),
	"T_MDATA":      NewTable("T_MDATA", convert, 2006),
	"T_TJ_DATA":    NewTable("T_TJ_DATA", convert, 2006),
	"T_PDATA":      NewTable("T_PDATA", convertPdata, 2006),
	"T_NDATA":      NewTable("T_NDATA", convertNdata, 2006),
	"T_VDATA":      NewTable("T_VDATA", convertVdata, 2006),
	"T_UTLANDDATA": NewTable("T_UTLANDDATA", convert, 2006),
	"T_MONTH":      NewTable("T_MONTH", convertProduct, 1957),
	"T_DIURNAL":    NewTable("T_DIURNAL", convertProduct, 2006),
}
