package port

import (
	kdvh "migrate/kdvh/db"
	"migrate/lard"
)

// TODO: move to lard package
type ParsedObs struct {
	data   *lard.DataObs
	text   *lard.TextObs
	legacy *lard.LegacyData
	flag   *lard.LegacyFlag
}

// TODO: move to lard package
type ParsedCsv struct {
	data   [][]any
	text   [][]any
	legacy [][]any
	flag   [][]any
}

func InitParsedCsv(capacity int) *ParsedCsv {
	return &ParsedCsv{
		data:   make([][]any, 0, capacity),
		text:   make([][]any, 0, capacity),
		legacy: make([][]any, 0, capacity),
		flag:   make([][]any, 0, capacity),
	}
}

func (p *ParsedCsv) Append(obs *ParsedObs) {
	if obs.data != nil {
		p.data = append(p.data, obs.data.ToRow())
	}
	if obs.text != nil {
		p.text = append(p.text, obs.text.ToRow())
	}
	if obs.legacy != nil {
		p.legacy = append(p.legacy, obs.legacy.ToRow())
	}
	if obs.flag != nil {
		p.flag = append(p.flag, obs.flag.ToRow())
	}
}

// Functions that try to recover the original pair of `controlinfo` and `useinfo` (see `flags/flags.go`)
// generated by Kvalobs for an observation, based on `KdvhObs.Flags` and `KdvhObs.Data`
// Different KDVH tables need different ways to perform this conversion.
//
// It returns a ParsedObs struct
type ConvertFunction func(*kdvh.Obs, *kdvh.TsInfo) (*ParsedObs, error)
type Table struct {
	TableName string // Name of the DATA table
	// TODO: remove this after dumping the elem tables
	ElemTableName string          // Name of the ELEM table
	Convert       ConvertFunction // How to dump a given combo of (element, station) for the given table
	ImportUntil   int
}

func NewTable(data, elem string, fn ConvertFunction, year int) *Table {
	return &Table{
		TableName:     data,
		ElemTableName: elem,
		Convert:       fn,
		ImportUntil:   year,
	}
}

func InitImportTables() []*Table {
	return []*Table{
		NewTable("T_EDATA", "T_ELEM_EDATA", convertEdata, 3000),
		NewTable("T_METARDATA", "T_ELEM_FDATA", convert, 3000),
		NewTable("T_ADATA", "T_ELEM_OBS", convert, 2006),
		NewTable("T_MDATA", "T_ELEM_OBS", convert, 2006),
		NewTable("T_TJ_DATA", "T_ELEM_OBS", convert, 2006),
		NewTable("T_PDATA", "T_ELEM_OBS", convertPdata, 2006),
		NewTable("T_NDATA", "T_ELEM_OBS", convertNdata, 2006),
		NewTable("T_VDATA", "T_ELEM_OBS", convertVdata, 2006),
		NewTable("T_UTLANDDATA", "T_ELEM_OBS", convert, 2006),
		NewTable("T_MONTH", "T_ELEM_MONTH", convertProduct, 1957),
		NewTable("T_DIURNAL", "T_ELEM_DIURNAL", convertProduct, 2006),
		// NewTable("T_HOMOGEN_DIURNAL", "", "T_ELEM_HOMOGEN_MONTH", convertProduct, 0),
		// NewTable("T_HOMOGEN_MONTH", "", "T_ELEM_HOMOGEN_MONTH", convertProduct, 0),
		// NewTable("T_DIURNAL_INTERPOLATED", "", "T_ELEM_DIURNAL", convertDiurnalInterpolated, 0),
	}
}
