---
- name: Get hostkey
  ansible.builtin.shell: |
    set -o pipefail
    ssh-keyscan '{{ ansible_host }}' | grep 'ecdsa-sha2-nistp256'
  args:
    executable: /bin/bash
  register: key
  changed_when: false
  delegate_to: localhost

- name: Assert we only have a single hostkey
  ansible.builtin.assert:
    that:
      - key.stdout_lines | length == 1
    fail_msg: More than one key grepped

- name: Add hostkey to localhost `known_hosts`
  ansible.builtin.known_hosts:
    name: "{{ ansible_host }}"
    state: present
    key: "{{ key.stdout }}"
    hash_host: true
  delegate_to: localhost

- name: Add users keys to authorized_keys
  ansible.posix.authorized_key:
    # username on the remotehost whose authorized keys are being modified
    user: ubuntu
    state: present
    key: "{{ item.key }}"
  loop: "{{ ssh_user_key_list }}"
  loop_control:
    label: "adding {{ item.name }} key to authorized_keys"
