[package]
name = "util"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "generate_partition_queries"

[dependencies]
bb8.workspace = true
bb8-postgres.workspace = true
chrono.workspace = true
postgres-types.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-util.workspace = true