[package]
name = "lard_tests"
version = "0.1.0"
edition.workspace = true

[features]
debug = []

[dependencies]
lard_egress = { path = "../egress" }
lard_ingestion = { path = "../ingestion", features = ["integration_tests"] }
chrono.workspace = true
chronoutil.workspace = true
util = { path = "../util" }
tokio.workspace = true
tokio-postgres.workspace = true
tokio-util.workspace = true
bb8.workspace = true
bb8-postgres.workspace = true
rove.workspace = true
rove_connector = { path = "../rove_connector" }
serde.workspace = true
futures.workspace = true
csv.workspace = true
reqwest = {version = "0.12.9", features = ["json"]}

[[bin]]
name = "prepare_postgres"
path = "src/main.rs"
test = false
bench = false
