[package]
name = "lard_tests"
version = "0.1.0"
edition.workspace = true

[features]
debug = []

[dependencies]
lard_egress = { path = "../egress", features = ["integration_tests"] }
lard_ingestion = { path = "../ingestion", features = ["integration_tests"] }
chrono.workspace = true
util = { path = "../util", features = ["integration_tests"] }
tokio.workspace = true
tokio-postgres.workspace = true
tokio-util.workspace = true
bb8.workspace = true
bb8-postgres.workspace = true
rdkafka.workspace = true
rust-s3.workspace = true
futures.workspace = true
reqwest.workspace = true 
jsonwebtoken.workspace = true
pg_interval.workspace = true
