---
- name: Create /mnt/ssd-data
  ansible.builtin.file:
    path: /mnt/ssd-data
    state: directory
    owner: ubuntu # change to postgres?
    group: ubuntu # change to postgres?
    mode: 'u=rw,g=rws,o=r'
  become: true

- name: Create ext4 filesystem on {{ mount_point }}
  community.general.filesystem:
    dev: '{{ mount_point }}'
    fstype: ext4
  become: true

- name: Read device information (always use unit when probing)
  community.general.parted:
    device: '{{ mount_point }}'
    unit: MiB
  register: sdb_info
  become: true

- name: Print out the device information
  ansible.builtin.debug:
    msg: "Partitions {{ sdb_info.partitions }}"

# this also changes the fstab so its still there when rebooted!
- name: Mount the disk from {{ mount_point }}
  ansible.posix.mount:
    path: /mnt/ssd-data
    src: '{{ mount_point }}'
    fstype: ext4
    state: mounted
  become: true

- name: Fetch the UUID of {{ mount_point }}
  ansible.builtin.command: blkid --match-tag UUID --output value '{{ mount_point }}'
  changed_when: false
  register: blkid_cmd
  become: true

- name: Print out the UUID
  ansible.builtin.debug:
    msg: "UUID {{ blkid_cmd.stdout }}"
