---
- name: Configure ssh
  hosts: lard
  remote_user: ubuntu
  gather_facts: false
  tags: ssh
  roles:
    - role: ssh

- name: Stagger unattended-upgrades reboot time
  hosts: lard
  remote_user: ubuntu
  gather_facts: true
  tags: unattended
  roles:
    - role: unattended_upgrades
      vars:
        unattended_upgrades_hour: "{{ 3 + (hostvars[inventory_hostname].pg_node_id / 12) }}"
        unattended_upgrades_min: "{{ (hostvars[inventory_hostname].pg_node_id * 5) % 60 }}"

- name: Configure postgres for replication
  hosts: lard
  remote_user: ubuntu
  gather_facts: true
  # TODO: it would be nice to have a host (dns?)
  # that always points to the primary
  vars:
    primary: lard-a # or provide via cmd '-e primary=...'
  roles:
    - role: pg
      vars:
        pg_version: 17
        pg_primary_ip: "{{ hostvars[primary].ansible_host }}"
        pg_mount_point: "{{ ostack_mount_point }}"

- name: Create what is needed for the bigip load balancers
  hosts: lard
  remote_user: ubuntu
  gather_facts: false
  tags: bigip
  tasks:
    - name: Bigip
      ansible.builtin.import_role:
        name: pg
        tasks_from: bigip.yml
      vars:
        pg_version: 17
        pg_mount_point: "{{ ostack_mount_point }}"

- name: Set up node and postgres exporters
  hosts: lard
  remote_user: ubuntu
  gather_facts: true
  tags: exporters
  roles:
    - role: prometheus.prometheus.node_exporter
      node_exporter_web_listen_address: "0.0.0.0:9001"
    - role: prometheus.prometheus.postgres_exporter
      postgres_exporter_name: "postgresql://lard_user:{{ pg_lard_user_password }}@localhost/lard"
      postgres_exporter_web_listen_address: "0.0.0.0:9002"
      postgres_exporter_enabled_collectors: ["stat_statements"]

- name: Set up backups
  hosts: lard
  remote_user: ubuntu
  gather_facts: true
  tags: backups
  roles:
    - role: backups
