---
lard:
  hosts:
    lard-a:
    lard-b:
  vars:
    primary: lard-a
    ostack_floating_ip: "{{ vault_ostack_floating_ip_production }}"
    backups_enabled: true
    deploy_kafka_group: "lard-production"
