---
- name: Setup networks and 2 vms
  hosts: servers
  gather_facts: false

  tasks:
    - name: Setup networks # noqa: run-once[task]
      ansible.builtin.include_role:
        name: networks
      delegate_to: localhost
      run_once: true

    - name: Setup VMs
      ansible.builtin.include_role:
        name: vm
      delegate_to: localhost
