---
- name: Rejoin
  hosts: servers
  remote_user: ubuntu
  roles:
    - role: rejoin
      vars:
        rejoin_vm_ip: "{{ ansible_host }}" # the current vm's ip
      when: ansible_host == rejoin_ip # only run on the one that needs to be rejoined
