---
# ansible-playbook -v -i inventory.yml -e recovery_filename=___ -e recovery_database=___ restore_on_staging.yml --ask-vault-pass
- name: Restore dump on staging
  hosts: staging
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: recovery
      vars:
        recovery_mount_point: '{{ ostack_mount_point }}'
        recovery_pg_version: 17
