---
- name: Switch the primary and standby / replica
  hosts: lard
  gather_facts: false
  remote_user: ubuntu
  # TODO: this can be probably done automatically if there are only two VMs?
  # pre_tasks:
  #   - name: Find server role
  vars:
    # provide via cmd '-e new=... -e old=...'
    old:
    new:
  roles:
    - role: switchover
      vars:
        switchover_old: "{{ old }}"
        switchover_new: "{{ new }}"
