---
- name: Format VMs
  ansible.builtin.import_role:
    name: ostack
    tasks_from: format_vm.yml
  tags: format

- name: Set postgres facts
  ansible.builtin.set_fact:
    pg_dir: "{{ pg_mount_point }}/postgresql/{{ pg_version }}/main"
    pg_venv: "{{ pg_mount_point }}/.venv/postgres"

- name: Install postgres
  ansible.builtin.import_tasks: configure/install_postgres.yml

# Needed to disable certain tasks, as replicas are read-only and can't run them
- name: Discover replication status
  community.postgresql.postgresql_query:
    login_db: "lard"
    login_host: "localhost"
    login_user: "lard_user"
    login_password: "{{ pg_lard_user_password }}"
    query: SELECT * FROM pg_stat_wal_receiver
  register: pg_stat_wal_receiver
  # This will fail on first run, as the lard user and db are not yet created. In this case
  # the following task will assume is_replica as false
  ignore_errors: true

- name: Set replication status fact
  ansible.builtin.set_fact:
    pg_is_replica: "{{ (pg_stat_wal_receiver.rowcount | default(0)) == 1 }}"

# In addition to replication status, we also need this to prevent accidentally
# wiping and re-cloning a replica that is already populated, as this takes ~2hrs
# per node in prod, and adds a lot of load to the primary
- name: Discover timeseries count
  community.postgresql.postgresql_query:
    login_db: "lard"
    login_host: "localhost"
    login_user: "lard_user"
    login_password: "{{ pg_lard_user_password }}"
    query: SELECT COUNT(*) FROM public.timeseries
  register: pg_timeseries_count_raw
  # This will fail on first run, as the lard user and db are not yet created. In this case
  # the following task will assert no timeseries exist
  ignore_errors: true

- name: Set timeseries_count fact
  ansible.builtin.set_fact:
    pg_timeseries_exist: "{{ (pg_timeseries_count_raw.query_result[0][\"count\"] | default(0)) != 0 }}"

- name: Print replication status and timeseries count
  ansible.builtin.debug:
    msg: "replication status: {{ pg_is_replica }}, timeseries_exist: {{ pg_timeseries_exist }}"

- name: Configure repmgr
  ansible.builtin.import_tasks: configure/repmgr.yml
  when: not pg_is_replica

- name: Setup primary and standby
  # Don't setup replication unless we have more than 1 node
  when: (groups['lard'] | length) > 1
  block:
    # This needs to be done after postgres installation
    - name: Share postgres SSH keys
      ansible.builtin.import_tasks: configure/ssh.yml

    - name: Create primary
      ansible.builtin.import_tasks: configure/create_primary.yml
      when:
        - ansible_host == pg_primary_ip
        - not pg_is_replica

    # This causes a full clone of the database from the primary, which is
    # expensive, so we only run it if the database is not populated.
    # Otherwise, we run the task below instead which only follows
    - name: Create standby
      ansible.builtin.import_tasks: configure/create_standby.yml
      when:
        - ansible_host != pg_primary_ip
        - not pg_is_replica
        - not pg_timeseries_exist

    - name: Set standby to follow
      ansible.builtin.import_tasks: configure/standby_follow.yml
      when:
        - ansible_host != pg_primary_ip
        - not pg_is_replica
        - pg_timeseries_exist

- name: Attach ipalias IP to the primary
  ansible.builtin.import_role:
    name: ostack
    tasks_from: attach_floating_ip.yml
  delegate_to: localhost
  when:
    - ansible_host == pg_primary_ip
    - not pg_is_replica
