---
- name: Set venv interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ pg_mount_point }}/.venv/postgres/bin/python3"
  tags: always

- name: Pre migrations
  when: ansible_host == pg_primary_ip
  tags: pre
  block:
    - name: Disable automatic reboot
      ansible.builtin.replace:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: (Unattended-Upgrade::Automatic-Reboot ).*;
        replace: '\1"false";'
      become: true

    - name: Delete replication slots
      community.postgresql.postgresql_query:
        login_db: lard
        query: >-
          SELECT pg_drop_replication_slot(slot_name)
          FROM pg_replication_slots
      become: true
      become_user: postgres

    - name: Disable replication
      community.postgresql.postgresql_alter_system:
        param: max_wal_senders
        value: 0
      become: true
      become_user: postgres

    - name: Disable wal summarization
      community.postgresql.postgresql_alter_system:
        param: summarize_wal
        value: "off"
      become: true
      become_user: postgres

    - name: Reduce wal level
      community.postgresql.postgresql_alter_system:
        param: wal_level
        value: "minimal"
      become: true
      become_user: postgres

    # TODO: currently we don't do archiving, so it's already off
    # - name: Disable archiving
    #   community.postgresql.postgresql_alter_system:
    #     param: archive_mode
    #     value: "off"
    #   become: true
    #   become_user: postgres

    - name: Restart postgres service
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
      become: true

- name: Truncate tables
  community.postgresql.postgresql_query:
    login_db: "{{ item }}"
    query:
      - TRUNCATE TABLE timeseries RESTART IDENTITY CASCADE
      - TRUNCATE TABLE legacy.data
      - TRUNCATE TABLE nonscalar_data
      - TRUNCATE TABLE labels.kvalobs
      - TRUNCATE TABLE labels.kdvh
      - TRUNCATE TABLE labels.met
  loop:
    - lard
    - lard_restricted
  become: true
  become_user: postgres
  tags: truncate, never
  when: ansible_host == pg_primary_ip

- name: Post migrations
  tags: post
  block:
    # NOTE: on both since they are not coupled at this moment
    - name: Enable replication
      community.postgresql.postgresql_alter_system:
        param: max_wal_senders
        value: 10
      become: true
      become_user: postgres

    - name: Reset wal level
      community.postgresql.postgresql_alter_system:
        param: wal_level
        value: "replica"
      become: true
      become_user: postgres

    - name: Reset wal summarization
      community.postgresql.postgresql_alter_system:
        param: summarize_wal
        value: "on"
      become: true
      become_user: postgres

    - name: Restart postgres service
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
      become: true

    - name: Recreate standby
      ansible.builtin.import_tasks: configure/create_standby.yml
      when: ansible_host != pg_primary_ip

    - name: Enable automatic reboot
      ansible.builtin.replace:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: (Unattended-Upgrade::Automatic-Reboot ).*;
        replace: '\1"true";'
      when: ansible_host == pg_primary_ip
      become: true
