when:
  - event: push
    branch: main
  - event: [pull_request, manual]

services:
  - name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432

steps:
  - name: build and test
    image: rust
    environment:
      CARGO_TERM_COLOR: always
      PG_CONN_STRING: "host=postgres user=postgres dbname=postgres password=postgres"
      LARD_CONN_STRING: "host=postgres user=postgres dbname=lard password=postgres"
      LARD_RESTRICTED_CONN_STRING: "host=postgres user=postgres dbname=lard_restricted password=postgres"
    commands:
      - cargo build -j 4 --workspace --tests
      - target/debug/setup_test_environment
      - cargo test --no-fail-fast -- --nocapture --test-threads=1
