when:
  - event: push
    branch: main
  - event: [pull_request, manual]

steps:
  - name: build and test
    when:
      event: [push, pull_request, manual]
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup component add clippy
      - rustup component add rustfmt
      - cargo fmt --all -- --check
      - cargo build -j 4 --workspace --tests
      - cargo clippy -j 4 --workspace --all-targets -- -D warnings
      - target/debug/setup_test_environment
      #- cargo test --no-fail-fast -- --nocapture --test-threads=1
