---
deploy_files:
  - src: lard_ingestion.service
    dest: /etc/systemd/system
    mode: "0664"
  - src: var_file
    dest: /etc/systemd/lard_ingestion.var
    mode: "0664"
  - src: "{{ playbook_dir }}/../target/release/lard_ingestion"
    dest: /usr/local/bin
    mode: "0755"
  - src: "{{ playbook_dir }}/../ingestion/resources"
    dest: /usr/local/bin
    mode: "0755"
