---
- name: Install s3cmd
  ansible.builtin.apt:
    pkg:
      - s3cmd
    update_cache: true
  become: true

- name: Move s3 config file # needs to be decrypted before its moved
  ansible.builtin.copy:
    src: .s3cfg
    dest: /home/ubuntu/
    mode: "0755"
  become: true

# backup to s3 in lard/backups bucket
- name: Backup Lard DB
  ansible.builtin.cron:
    name: "backup lard"
    minute: "0"
    hour: "3,15" # backup daily at 3am and 3pm
    job: "sudo -u postgres pg_dump lard | s3cmd put - s3://lard/backups/lard__$(date +%Y%m%d%H%M%S)"

- name: Backup globals
  ansible.builtin.cron:
    name: "backup globals"
    minute: "0"
    hour: "0"
    day: "1" # only backup globals once a month (change infrequently?)
    job: "sudo -u postgres pg_dumpall --globals-only | s3cmd put - s3://lard/backups/globals__$(date +%Y%m%d%H%M%S)"
